version: 2.1

executors:
  my-executor:
    working_directory: ~/repo
    docker:
      - image: circleci/node:lts

commands:
  my-command:
    description: "A very simple command for demonstration purposes"
    parameters:
      to:
        type: string
        default: "Hello World"
    steps:
      - run: echo << parameters.to >>

jobs:
  my-job:
    executor: my-executor
    steps:
      - checkout
      - my-command:
          to: 'Hello CircleCI'

workflows:
  my-workflow:
    jobs:
      - my-job:
          filters:
            branches:
              only: master
